### ISSUE TITLE
phylophlan_metagenomic.py - offline usage

### ISSUE THREAD

**Issue by fahad3li** [biobakery/phylophlan#112]
This check was causing some grief for me on HPC clusters without internet access:

`if (    not os.path.exists(os.path.join(args.database_folder, args.database)) or
                not os.path.exists(os.path.join(args.database_folder, args.mapping)) or
                not os.path.exists(os.path.join(args.database_folder, args.database + '.md5'))    )`

Even if the databases are pre-downloaded, the check will fail because the '.tar' extension is not explicit in the first line. Adding it in will prevent the script from getting hung on the download step.

**Comment by fasnicar** [comment]
Hi there and thanks for reporting this. The `.tar.` there is not specified because the check is for the extracted database. If you add `.tar` but for some reason the db was downloaded but not properly extracted, it won't be extracted and there will not be the files available for the execution.

When working with machines without internet access, my suggestion is to run it on a machine with internet to ensure the setup is ok and everything is working. Then, when running it from the offline machines and specifying the same path to the db previously set up, there should not be other issues.


Many thanks,
Francesco
