### ISSUE TITLE
Tree of life at nucleotide level

### ISSUE THREAD

**Issue by gunturus** [biobakery/phylophlan#26]
Is there a way to make the tree of life using phylophan database at the nucleotide level? The default phylophan database only has a protein database from my understanding.

**Comment by fasnicar** [comment]
Hello, you can use the `--force_nucleotides` param to force PhyloPhlAn building a phylogeny based on nucleotides instead of proteins, as detailed [here](https://github.com/biobakery/phylophlan/wiki#nucleotide-or-amino-acid) in the wiki.
Also, you have to ri-generate the configuration file specifying the same `--force_nucleotides` param to make the proper configuration file for this analysis.
Note that (1) this works only if your inputs are all genomes, as proteomes (if presents among your inputs) will not be included in the analysis, and (2) whether the database is made of genes or proteins, instead, won't change in this case, so you can use the `phylophlan` database.

If I may, my personal comment on this is not to do a tree of life using nucleotides because the alignment positions will be 3 times longer than using proteins and this affects both the MSA and the phylogeny inference steps, which will take longer and most likely much more than 3 times the time of using proteins.

**Comment by fasnicar** [comment]
I see and I understand better now why you want to do that.
Have you checked out the tutorial of [phylophlan_metagenomic](https://github.com/biobakery/biobakery/wiki/PhyloPhlAn-3.0:-Example-03:-Metagenomic-application)?
Is the Arthrobacter coming from phylophlan_metagenomic? If not, you can use phylophlan_metagenomic to find the closest SGB to your bins and you can also add them to your analysis, like in the [Proteobacteria tutorial](https://github.com/biobakery/biobakery/wiki/PhyloPhlAn-3.0:-Example-05:-Proteobacteria).

I hope this helps
