### ISSUE TITLE
Documentation does not say how to download databases

### ISSUE THREAD

**Issue by mw55309** [biobakery/phylophlan#40]
Hello

Section https://github.com/biobakery/phylophlan/wiki#databases says "PhyloPhlAn 3.0 is able to automatically download two databases of universal markers for prokaryotes:" but does not then go on to say how phylophlan does this, or what commands a user needs to execute to download those databases.

When installing from conda, no databases come with the install:

```sh
phylophlan --database_list --diversity low
Available databases in "phylophlan_databases/":
```

**Comment by fasnicar** [comment]
Hello Mick,
Thanks for trying PhyloPhlAn. The two available databases are `phylophlan` and `amphora2` and are automatically downloaded only when running PhyloPhlAn. That's why you don't see and database right after the installation.

We can definitely make this more clear from the documentation.

Many thanks,
Francesco

**Comment by mw55309** [comment]
Great, thank you 👍
