### ISSUE TITLE
Problem with Example 01: S. aureus

### ISSUE THREAD

**Issue by Shiqing-Nie** [biobakery/phylophlan#46]
Hi developer,I met the error below. How could I deal with it? 
I installed it with Conda with command:   conda create -n "nsqphy" -c bioconda phylophlan=3.0
generating the four default configuration files with command :   phylophlan_write_default_configs.sh  phylo

when I follow the instructions of Example 01: S. Aureus at step 2
phylophlan_setup_database -g s__Staphylococcus_aureus \
    -o examples/01_saureus/ \
    --verbose 2>&1 | tee logs/phylophlan_setup_database.log
I got the error information immediately:  
[e] ciao

![image](https://user-images.githubusercontent.com/50396399/94666799-84754400-0340-11eb-98b9-5aa2b5e794bf.png)

**Comment by fasnicar** [comment]
Hi, and thanks for reporting this. Indeed my fault, sorry about that. I forgot to remove an early forced exit when doing some development last time. I'm really sorry about it.
I have fixed it in the repository code, but it will take a bit longer to have a new package version in Bioconda, so can you please install PhyloPhlAn from the repository?
Otherwise, you'll need to wait 2/3 days before having a new package version in Bioconda that you can install with the fix.

Many thanks,
Francesco

**Comment by Shiqing-Nie** [comment]
Hi developer, I just install PhyloPhlAn from the repository with command :  python setup.py install


Then, I follow the instructions of Example 01: S. Aureus at step 2 and get another error:
phylophlan_setup_database.py version 3.0.22 (30 September 2020)

Command line: /public/home/sk_ljh/conda/yes/bin/phylophlan_setup_database -g s__Staphylococcus_aureus -o ../../examples/01_saureus/ --verbose

Setting output folder "../../examples/01_saureus/s__Staphylococcus_aureus"
Setting db_name to "s__Staphylococcus_aureus"
Arguments: {'input': '../../examples/01_saureus/s__Staphylococcus_aureus', 'get_core_proteins': 's__Staphylococcus_aureus', 'database_update': False, 'output': '../../examples/01_saureus/s__Staphylococcus_aureus', 'db_name': 's__Staphylococcus_aureus', 'input_extension': '.faa', 'db_type': None, 'output_extension': '.faa', 'overwrite': False, 'verbose': True}
Creating output folder "../../examples/01_saureus/s__Staphylococcus_aureus"
Downloading "https://www.dropbox.com/s/jrituki21vx6p30/taxa2core.txt?dl=1" to "taxa2core.txt"
[e] unable to download "https://www.dropbox.com/s/jrituki21vx6p30/taxa2core.txt?dl=1"
Traceback (most recent call last):
  File "/public/home/sk_ljh/conda/yes/bin/phylophlan_setup_database", line 33, in <module>
    sys.exit(load_entry_point('PhyloPhlAn==3.0.1', 'console_scripts', 'phylophlan_setup_database')())
  File "/public/home/sk_ljh/conda/yes/lib/python3.7/site-packages/PhyloPhlAn-3.0.1-py3.7.egg/phylophlan/phylophlan_setup_database.py", line 400, in phylophlan_setup_database
    taxa2core_file_latest = database_update(update=args.database_update, verbose=args.verbose)
  File "/public/home/sk_ljh/conda/yes/lib/python3.7/site-packages/PhyloPhlAn-3.0.1-py3.7.egg/phylophlan/phylophlan_setup_database.py", line 178, in database_update
    with open(taxa2core_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'taxa2core.txt'


It seems that I can't download the database. What should I do? I am in China.

**Comment by fasnicar** [comment]
Hi, Dropbox appears to not be accessible from China. Those files are still in Dropbox because it is much easier to update them when needed, while the databases were moved to Zenodo so those should be accessible from China.
I just uploaded the files you should need to Drive here: https://drive.google.com/drive/folders/16EO-42NbEMF8FY4XedKAHeYoGMJJspgR?usp=sharing
You should download the two files manually and put them in the folder where you're executing PhyloPhlAn.

Many thanks,
Francesco
